### ISSUE TITLE
chore: typo on example

### ISSUE THREAD

**Issue by samuelthan** [OP5dev/Prompt-AI#14]
Was using this example workflow to test out the Prompt-AI. Discovered that there is a typo referencing top_p, 
i think it should be top-p. 

```
on:
  pull_request:
  push:
    branches: main

jobs:
  provision:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
      models: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Provision Terraform
        id: provision
        uses: op5dev/tf-via-pr@v13
        with:
          working-directory: env/dev
          command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}

      - name: Troubleshoot Terraform
        if: failure()
        uses: op5dev/prompt-ai@v2
        with:
          model: openai/gpt-4.1-mini
          system-prompt: You are a helpful DevOps assistant and expert at debugging Terraform errors.
          user-prompt: Troubleshoot the following Terraform output; ${{ steps.provision.outputs.result }}
          max-tokens: 500
          temperature: 0.7
          top_p: 0.9
```
